#!/usr/bin/env node
import { canonicalApexRoot } from './apex-paths.mjs';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { requireRouterAction } from './apex-runtime-guard.mjs';

const apexRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const validator = path.join(apexRoot, 'scripts', 'apex-validate.mjs');
const ignored = new Set(['.git', '.apex', 'node_modules', 'dist', 'build', 'coverage', '.next', '.nuxt', 'vendor', 'target']);
const sourceExtensions = new Set(['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx', '.vue', '.svelte', '.html', '.htm', '.ejs', '.hbs', '.pug', '.php', '.py', '.java', '.go', '.rb', '.cs']);
function die(message) { console.error(`Project intake failed: ${message}`); process.exit(1); }
function readJson(file) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (error) { die(`${file}: ${error.message}`); } }
function write(file, value) { fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); }
function assertCanonicalRoot() { if (fs.realpathSync(apexRoot) !== fs.realpathSync(canonicalApexRoot)) die(`APEX must run from canonical root: ${canonicalApexRoot}`); }
function rel(root, file) { return path.relative(root, file).split(path.sep).join('/'); }
function exists(root, file) { return fs.existsSync(path.join(root, file)); }
function walk(root, current = root, files = [], limit = 12000) { if (files.length >= limit) return files; for (const entry of fs.readdirSync(current, { withFileTypes: true })) { if (ignored.has(entry.name)) continue; const absolute = path.join(current, entry.name); if (entry.isDirectory()) walk(root, absolute, files, limit); else if (entry.isFile() && sourceExtensions.has(path.extname(entry.name))) files.push(rel(root, absolute)); if (files.length >= limit) break; } return files; }
function infer(manifest, root, files) { const dependencies = { ...(manifest?.dependencies || {}), ...(manifest?.devDependencies || {}) }; const has = name => Boolean(dependencies[name]); const runtime = []; const frameworks = []; if (manifest) runtime.push('node'); if (has('react') || files.some(file => /\.(jsx|tsx)$/.test(file))) frameworks.push('react'); if (has('next') || exists(root, 'next.config.js') || exists(root, 'next.config.mjs')) frameworks.push('next'); if (has('vue') || files.some(file => file.endsWith('.vue'))) frameworks.push('vue'); if (has('svelte') || files.some(file => file.endsWith('.svelte'))) frameworks.push('svelte'); if (has('@angular/core')) frameworks.push('angular'); if (has('express')) frameworks.push('express'); if (has('fastify')) frameworks.push('fastify'); if (files.some(file => file.endsWith('.py'))) runtime.push('python'); if (exists(root, 'go.mod')) runtime.push('go'); if (exists(root, 'pom.xml') || exists(root, 'build.gradle')) runtime.push('java'); return { runtime: [...new Set(runtime)], frameworks: [...new Set(frameworks)] }; }
function entrypoints(files) { return files.filter(file => /(^|\/)(main|index|app|server|client|layout|page)\.(js|jsx|mjs|cjs|ts|tsx|vue|svelte|py)$/.test(file)).slice(0, 80); }
function routes(files) { return files.filter(file => /(^|\/)(pages|app|routes|router|views)\//.test(file) || /(^|\/)(routes?|router)\.(js|jsx|ts|tsx|py)$/.test(file)).slice(0, 160); }
function testCommands(scripts = {}) { return Object.keys(scripts).filter(name => /^(test|test:|lint$|lint:|typecheck|check$|e2e|e2e:|build$)/.test(name)).map(id => ({ id: `package-${id.replace(/[^a-zA-Z0-9]+/g, '-')}`, command: `npm run ${id}`, purpose: /^(test|e2e)/.test(id) ? 'test' : id === 'build' ? 'build' : 'static-check' })); }
function adapterRecommendation(manifest, detected, files) { const dependencies = { ...(manifest?.dependencies || {}), ...(manifest?.devDependencies || {}) }; if (['@micro-zoe/micro-app','qiankun','@alifd/lowcode-engine'].some(name => dependencies[name]) || files.some(file => /(^|\/)(shell|micro-app|lowcode|platform)\//i.test(file))) return { id: 'platform-shell', path: 'adapters/examples/platform-shell/adapter.md', confidence: 'high', reasons: ['platform shell or private-component indicators detected'] }; if (['jquery','requirejs','single-spa'].some(name => dependencies[name]) || files.some(file => /\.(html|htm|ejs|hbs|pug)$/.test(file)) && !detected.frameworks.some(item => ['react','vue','svelte'].includes(item))) return { id: 'legacy-multi-entry', path: 'adapters/examples/legacy-multi-entry/adapter.md', confidence: 'high', reasons: ['legacy runtime or server-template indicators detected'] }; if (detected.frameworks.includes('vue')) return { id: 'vue-enterprise', path: 'adapters/examples/vue-enterprise/adapter.md', confidence: 'high', reasons: ['Vue source or dependency detected'] }; if (detected.frameworks.includes('react')) return { id: 'react-saas', path: 'adapters/examples/generic-saas/adapter.md', confidence: 'high', reasons: ['React source or dependency detected'] }; return { id: 'generic-saas', path: 'adapters/examples/generic-saas/adapter.md', confidence: 'low', reasons: ['no specialized runtime pattern detected; user review required'] }; }
const [command, runArg, projectArg] = process.argv.slice(2); if (command === 'scan' && runArg) { try { requireRouterAction(path.resolve(runArg), 'collect_existing_baseline'); } catch (error) { die(error.message); } } assertCanonicalRoot(); if (command !== 'scan' || !runArg || !projectArg) die('usage: scan <run-dir> <project-root>'); const runDir = path.resolve(runArg); const projectRoot = path.resolve(projectArg); const stateFile = path.join(runDir, 'state.json'); if (!fs.existsSync(stateFile)) die(`run state does not exist: ${stateFile}`); if (!fs.statSync(projectRoot).isDirectory()) die(`project root is not a directory: ${projectRoot}`); const manifestFile = path.join(projectRoot, 'package.json'); const manifest = fs.existsSync(manifestFile) ? readJson(manifestFile) : null; const files = walk(projectRoot); const detected = infer(manifest, projectRoot, files); const lockfiles = ['package-lock.json', 'pnpm-lock.yaml', 'yarn.lock', 'bun.lockb']; const packageManager = lockfiles.find(file => exists(projectRoot, file))?.replace(/-lock\.json$|-lock\.yaml$|\.lock$|\.lockb$/g, '') || (manifest ? 'npm-unspecified' : 'not-detected'); const inventory = { schemaVersion: '3.0', capturedAt: new Date().toISOString(), projectRoot, runtime: detected.runtime, frameworks: detected.frameworks, packageManager, adapterRecommendation: adapterRecommendation(manifest, detected, files), scripts: manifest?.scripts || {}, entrypoints: entrypoints(files), routeCandidates: routes(files), testCommands: testCommands(manifest?.scripts), ignoredPaths: [...ignored].sort(), warnings: [] }; if (!manifest) inventory.warnings.push('package.json not found; no Node command was inferred'); if (!inventory.entrypoints.length) inventory.warnings.push('No conventional code entrypoint was found; review project structure manually'); if (!inventory.routeCandidates.length) inventory.warnings.push('No conventional route candidate was found; inspect routing manually'); if (!inventory.testCommands.length) inventory.warnings.push('No package test/build/lint script was inferred; supply a verification plan explicitly'); const output = path.join(runDir, 'project-inventory.json'); write(output, inventory); const validation = spawnSync(process.execPath, [validator, 'validate', 'project-inventory.schema.json', output], { encoding: 'utf8' }); if (validation.status !== 0) die((validation.stderr || validation.stdout).trim()); const state = readJson(stateFile); state.artifacts.projectInventory = 'project-inventory.json'; state.revision = Number(state.revision || 0) + 1; state.updatedAt = new Date().toISOString(); write(stateFile, state); console.log(JSON.stringify({ inventory: output, frameworks: inventory.frameworks, adapterRecommendation: inventory.adapterRecommendation, entrypoints: inventory.entrypoints.length, routeCandidates: inventory.routeCandidates.length, testCommands: inventory.testCommands.length, warnings: inventory.warnings }));
