#!/usr/bin/env node
/** Freezes the concrete source identity for every visual node before code generation. */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { requireRouterAction } from './apex-runtime-guard.mjs';

const apexRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const canonicalApexRoot = '/Users/fredyw/.codex/apex/APEX';
const hostSkills = new Set(['ui-ux-pro-max-skill', 'shadcn-ui-reference', 'motion-ai-kit', 'framer-motion', 'react-bits', 'better-icons', 'google-design-md', 'impeccable', 'taste-skill']);
function die(message) { console.error(`Visual source failed: ${message}`); process.exit(1); }
function read(file) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (error) { die(`${file}: ${error.message}`); } }
function write(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); }
function hash(file) { return `sha256:${crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}`; }
const [command, runArg, inputArg] = process.argv.slice(2);
if (fs.realpathSync(apexRoot) !== fs.realpathSync(canonicalApexRoot)) die(`APEX must run from canonical root: ${canonicalApexRoot}`);
if (command !== 'compile' || !runArg || !inputArg) die('usage: visual-source.mjs compile <run-dir> <visual-source-input.json>');
const runDir = path.resolve(runArg); try { requireRouterAction(runDir, 'compile_visual_bundle'); } catch (error) { die(error.message); }
const stateFile = path.join(runDir, 'state.json'), state = read(stateFile), input = read(path.resolve(inputArg));
if (input.schemaVersion !== '3.0' || !Array.isArray(input.sources) || !Array.isArray(input.bindings)) die('source manifest needs schemaVersion 3.0, sources, and bindings');
const visualReference = read(path.join(runDir, state.artifacts.visualReference || 'visual-reference.json'));
if (input.visualReferenceHash !== visualReference.referenceImage?.sha256) die('source manifest must bind the current approved visual reference image');
if (!state.artifacts.runtimeSourceLock || !state.artifacts.runtimeVisualBaseline) die('a runtime source lock and runtime visual baseline are required before freezing visual sources');
const runtimeLock = read(path.join(runDir, state.artifacts.runtimeSourceLock));
const runtimeBaseline = read(path.join(runDir, state.artifacts.runtimeVisualBaseline));
if (runtimeBaseline.sourceLockHash !== hash(path.join(runDir, state.artifacts.runtimeSourceLock)) || runtimeBaseline.referenceImage.sha256 !== visualReference.referenceImage.sha256) die('runtime visual baseline is not bound to the current source lock and approved reference image');
const visualPlan = read(path.join(runDir, state.artifacts.visualExecutionPlan || 'visual-execution-plan.json')); const planSelections = new Map((visualPlan.sourceSelections || []).map(item => [item.id, item])); const planAnalysis = visualPlan.selectionAnalysis || {}; const planCapabilities = new Set(planAnalysis.designCapabilities || []);
const aestheticSkills = new Set(['ui-ux-pro-max-skill', 'impeccable', 'taste-skill']);
// The visual-plan compiler requires this narrative. The fallback keeps focused source-only
// contract fixtures backwards-compatible; a Router-created plan can never rely on it.
const narrative = visualPlan.deliveryNarrative || { mode: state.track === 'existing' ? 'existing-iteration' : 'greenfield-selection' };
if ((state.track === 'greenfield' && narrative.mode !== 'greenfield-selection') || (state.track === 'existing' && narrative.mode !== 'existing-iteration')) die('visual sources require the track-specific confirmed delivery narrative');
if (!planCapabilities.has('google-design-md') || ![...planCapabilities].some(capability => aestheticSkills.has(capability)) || !planAnalysis.designContract?.path || !/^sha256:[a-f0-9]{64}$/.test(planAnalysis.designContract.sha256 || '') || !Array.isArray(planAnalysis.designContract.rules) || planAnalysis.designContract.rules.length < 4 || !planAnalysis.aestheticAssessment?.qualityRationale || !Array.isArray(planAnalysis.aestheticAssessment.coherenceChecks) || planAnalysis.aestheticAssessment.coherenceChecks.length < 5 || !Array.isArray(planAnalysis.libraryComparisons) || planAnalysis.libraryComparisons.length < 3) die('visual sources require the confirmed DESIGN.md contract, aesthetic coherence assessment, and multi-library comparison record');
if ((input.designCapabilities || []).some(capability => !planCapabilities.has(capability))) die('designCapabilities must be selected in the confirmed visual-plan analysis');
const registry = fs.readFileSync(path.join(apexRoot, 'registry', 'assets', 'online-sources.yaml'), 'utf8');
const designCapabilities = input.designCapabilities || [];
if (!Array.isArray(designCapabilities) || designCapabilities.some(capability => !hostSkills.has(capability))) die('designCapabilities may only contain registered design skills');
const sources = new Map(); for (const source of input.sources) { if (!source.id || sources.has(source.id) || !source.planSourceSelectionId || !['layout','component','style','icon','font','content','motion','asset','chart','diagram'].includes(source.kind) || !source.sourceType || !source.sourceId || !source.resourceId || !source.version || !source.parameters || typeof source.parameters !== 'object') die(`invalid source: ${source.id || '<unknown>'}`); const selection = planSelections.get(source.planSourceSelectionId); if (!selection || selection.kind !== source.kind || selection.sourceType !== source.sourceType || selection.sourceId !== source.sourceId || selection.resourceId !== source.resourceId || selection.version !== source.version || JSON.stringify(selection.parameters) !== JSON.stringify(source.parameters)) die(`source is not identical to a confirmed visual-plan selection: ${source.id}`); if (source.sourceType === 'host-skill' || source.sourceType === 'registry') die(`non-executable reference source is forbidden: ${source.id}`); const patterns = (runtimeLock.patterns || []).filter(pattern => pattern.sourceSelectionId === source.planSourceSelectionId); const nativeSelection = (runtimeLock.nativeSelections || []).find(item => item.id === source.planSourceSelectionId); if (selection.materialization !== 'runtime-package' && !nativeSelection) die(`native or project source was not rendered in the runtime baseline: ${source.id}`); if (source.sourceType === 'approved-candidate' && !patterns.length) die(`selected source was not used by a complete rendered runtime pattern: ${source.id}`); sources.set(source.id, { ...source, materialization: selection.materialization, runtimePatternIds: patterns.map(pattern => pattern.id), resolvedFiles: patterns.flatMap(pattern => pattern.files || []) }); }
if (sources.size !== planSelections.size || [...planSelections.keys()].some(id => ![...sources.values()].some(source => source.planSourceSelectionId === id))) die('every confirmed visual-plan source selection must be frozen in the visual source manifest');
const bindings = new Map(); for (const binding of input.bindings) { if (!binding.visualNode || bindings.has(binding.visualNode) || !binding.runtimeTarget?.length || !binding.selector || !binding.implementation) die(`invalid visual binding: ${binding.visualNode || '<unknown>'}`); for (const [field, kind] of [['layoutSourceId','layout'], ['componentSourceId','component'], ['styleSourceId','style'], ['fontSourceId','font'], ['contentSourceId','content']]) { const source = sources.get(binding[field]); if (!source || source.kind !== kind) die(`${binding.visualNode}: ${field} must reference a ${kind} source`); } for (const id of [...(binding.iconSourceIds || []), ...(binding.assetSourceIds || [])]) if (!sources.has(id)) die(`${binding.visualNode}: missing optional source ${id}`); bindings.set(binding.visualNode, binding); }
for (const binding of input.bindings) if (!runtimeLock.patterns.some(pattern => pattern.visualNodes.includes(binding.visualNode)) && !runtimeLock.nativeSelections?.some(selection => selection.visualNodes.includes(binding.visualNode))) die(`${binding.visualNode}: no complete runtime source is locked for this visual node`);
const outputBindings = input.bindings.map(binding => { const ids = [binding.layoutSourceId, binding.componentSourceId, binding.styleSourceId, binding.fontSourceId, binding.contentSourceId, ...(binding.iconSourceIds || []), ...(binding.assetSourceIds || [])].sort(); return { ...binding, sourceMarker: `apex-source-${crypto.createHash('sha256').update(`${binding.visualNode}\0${ids.join('\0')}`).digest('hex').slice(0, 16)}` }; });
const output = { schemaVersion: '3.0', visualReferenceHash: input.visualReferenceHash, deliveryNarrative: narrative, designCapabilities, designContract: planAnalysis.designContract, aestheticAssessment: planAnalysis.aestheticAssessment, libraryComparisons: planAnalysis.libraryComparisons, sources: [...sources.values()], bindings: outputBindings, source: { path: path.relative(runDir, path.resolve(inputArg)), sha256: hash(path.resolve(inputArg)) } };
write(path.join(runDir, 'visual-source-manifest.json'), output); state.artifacts.visualSourceManifest = 'visual-source-manifest.json'; state.revision = Number(state.revision || 0) + 1; state.updatedAt = new Date().toISOString(); write(stateFile, state);
console.log(JSON.stringify({ visualSourceManifest: path.join(runDir, 'visual-source-manifest.json'), sources: sources.size, bindings: bindings.size }));
